In [1]:
import pandas as pd
import codecs
import numpy as np
import math
import csv
import scipy as sc
from sklearn import preprocessing
import matplotlib.pyplot as plt
from scipy import signal
import openpyxl
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

from matplotlib import pylab as plt
import seaborn as sns
import sklearn
from numpy.linalg import svd
from keijzer import *
from keras import activations
import math

## Import Data & Preprocessing

In [2]:
data_path = 'C:/Users/smartgrid_AI/Desktop/windpower_ramprate/ercot_2020.csv'
data_source1 = pd.read_csv(data_path)
dat_source1 = pd.DataFrame(data_source1)
#dat_source1 = dat_source1.iloc[:-3,:]

data_path = 'C:/Users/smartgrid_AI/Desktop/windpower_ramprate/ercot_2021.csv'
data_source2 = pd.read_csv(data_path)
dat_source2 = pd.DataFrame(data_source2)
dat_source2 = dat_source2.iloc[:8761,:9]

data_path = 'C:/Users/smartgrid_AI/Desktop/windpower_ramprate/ercot_2022.csv'
data_source3 = pd.read_csv(data_path)
dat_source3 = pd.DataFrame(data_source3)
dat_source3 = dat_source3.iloc[:8760,:9]

data_path = 'C:/Users/smartgrid_AI/Desktop/windpower_ramprate/ercot_2023.csv'
data_source4 = pd.read_csv(data_path)
dat_source4 = pd.DataFrame(data_source4)
dat_source4 = dat_source4.iloc[:8760,:9]

dat_arr1 = np.array(dat_source1)
dat_arr2 = np.array(dat_source2)
dat_arr3 = np.array(dat_source3)
dat_arr4 = np.array(dat_source4)

dat_arr = np.concatenate([dat_arr1, dat_arr2, dat_arr3, dat_arr4],axis=0)
dat_arr.shape # 8784, 8761, 8760, 8760

dat_source = pd.DataFrame(dat_arr, columns=['Time-Date stamp','Date','ERCOT Load','Total Wind Output','Total Wind Installed','Wind Output, % of Load','Wind Output, % of Installed','1-hr MW change','1-hr % change'])
dat_source

Time-Date stamp    Date ERCOT Load Total Wind Output  \
0      01-01-2020 00:00:00  Jan-01      36823             12335   
1      01-01-2020 01:00:00  Jan-01      36511             13300   
2      01-01-2020 02:00:00  Jan-01      36022             13586   
3      01-01-2020 03:00:00  Jan-01      35790             14107   
4      01-01-2020 04:00:00  Jan-01      35642             14887   
...                    ...     ...        ...               ...   
35060  12-31-2023 20:00:00  Dec-31      44887             17161   
35061  12-31-2023 21:00:00  Dec-31      44013             18301   
35062  12-31-2023 22:00:00  Dec-31      43280             18607   
35063  12-31-2023 23:00:00  Dec-31      42319             17866   
35064  01-01-2024 00:00:00  Jan-01      41682             15869   

      Total Wind Installed Wind Output, % of Load Wind Output, % of Installed  \
0                    27040                   33.5                      45.617   
1                    27040                   36.4                      49.187   
2                    27040                   37.7                      50.245   
3                    27040                   39.4                      52.171   
4                    27040                   41.8                      55.055   
...                    ...                    ...                         ...   
35060                38631                  38.23                       44.42   
35061                38631                  41.58                       47.37   
35062                38631                  42.99                       48.17   
35063                38631                  42.22                       46.25   
35064                38631                  38.07                       41.08   

      1-hr MW change 1-hr % change  
0                NaN           NaN  
1              965.4         7.826  
2              286.2         2.152  
3              520.9         3.834  
4              779.6         5.527  
...              ...           ...  
35060           2858         19.99  
35061           1139          6.64  
35062            307          1.67  
35063           -741         -3.98  
35064          -1996        -11.17  

[35065 rows x 9 columns]

### Dividing by Installed Capacity & Preprocessing

In [3]:
dat = pd.DataFrame()
dat['MW % change'] = np.array(dat_source.iloc[1:,3], dtype=float)-np.array(dat_source.iloc[0:-1,3], dtype=float)
dat['MW % change'] = np.divide(np.array(dat['MW % change']),np.array(dat_source.iloc[1:,4]))*100
dat['Total Wind Output'] = np.divide(np.array(dat_source.iloc[1:,3]), np.array(dat_source.iloc[1:,4]))

dat

MW % change Total Wind Output
0         3.56879          0.491864
1         1.05769          0.502441
2         1.92678          0.521709
3         2.88462          0.550555
4       -0.580621          0.544749
...           ...               ...
35059      7.3982          0.444229
35060       2.951          0.473739
35061     0.79211           0.48166
35062    -1.91815          0.462478
35063    -5.16942          0.410784

[35064 rows x 2 columns]

In [4]:
ramp_ratio = 20
load_ratio = 10
year_arr = np.concatenate([np.ones(8784)*2020, np.ones(8760)*2021, np.ones(8760)*2022, np.ones(8760)*2023])
year_df = pd.DataFrame(year_arr, columns=['Year'], dtype=int)
wind_df = pd.concat([year_df, dat], axis=1)
wind_df

Year MW % change Total Wind Output
0      2020     3.56879          0.491864
1      2020     1.05769          0.502441
2      2020     1.92678          0.521709
3      2020     2.88462          0.550555
4      2020   -0.580621          0.544749
...     ...         ...               ...
35059  2023      7.3982          0.444229
35060  2023       2.951          0.473739
35061  2023     0.79211           0.48166
35062  2023    -1.91815          0.462478
35063  2023    -5.16942          0.410784

[35064 rows x 3 columns]

In [5]:
wind_df = wind_df.reset_index(drop=True)

std_scaler = sklearn.preprocessing.MinMaxScaler()
std_scaler_load = sklearn.preprocessing.MinMaxScaler()
std_scaler_ramp = sklearn.preprocessing.MinMaxScaler()

wind_df[['Total Wind Output']] = std_scaler.fit_transform(wind_df[['Total Wind Output']])
wind_df[['MW % change']] = std_scaler_ramp.fit_transform(wind_df[['MW % change']])
wind_df = wind_df.iloc[:-1,:]
wind_df

Year  MW % change  Total Wind Output
0      2020     0.620197           0.644724
1      2020     0.544580           0.658617
2      2020     0.570751           0.683924
3      2020     0.599594           0.721813
4      2020     0.495246           0.714187
...     ...          ...                ...
35058  2023     0.774643           0.484984
35059  2023     0.735512           0.582157
35060  2023     0.601593           0.620917
35061  2023     0.536583           0.631322
35062  2023     0.454969           0.606127

[35063 rows x 3 columns]

In [6]:
ramp_df = pd.DataFrame(wind_df)
ramp_df.columns=['Year', 'Wind Change', 'Wind Output']
ramp_df

Year  Wind Change  Wind Output
0      2020     0.620197     0.644724
1      2020     0.544580     0.658617
2      2020     0.570751     0.683924
3      2020     0.599594     0.721813
4      2020     0.495246     0.714187
...     ...          ...          ...
35058  2023     0.774643     0.484984
35059  2023     0.735512     0.582157
35060  2023     0.601593     0.620917
35061  2023     0.536583     0.631322
35062  2023     0.454969     0.606127

[35063 rows x 3 columns]

## Validation of Independency between Wind Power Generation and Ramp Rate

In [7]:
from __future__ import division
import numpy as np
from scipy.stats import gamma

def rbf_dot(pattern1, pattern2, deg):
	size1 = pattern1.shape
	size2 = pattern2.shape

	G = np.sum(pattern1*pattern1, 1).reshape(size1[0],1)
	H = np.sum(pattern2*pattern2, 1).reshape(size2[0],1)

	Q = np.tile(G, (1, size2[0]))
	R = np.tile(H.T, (size1[0], 1))

	H = Q + R - 2* np.dot(pattern1, pattern2.T)

	H = np.exp(-H/2/(deg**2))

	return H


def hsic_gam(X, Y, alph = 0.5):
	"""
	X, Y are numpy vectors with row - sample, col - dim
	alph is the significance level
	auto choose median to be the kernel width
	"""
	n = X.shape[0]

	# ----- width of X -----
	Xmed = X

	G = np.sum(Xmed*Xmed, 1).reshape(n,1)
	Q = np.tile(G, (1, n) )
	R = np.tile(G.T, (n, 1) )

	dists = Q + R - 2* np.dot(Xmed, Xmed.T)
	dists = dists - np.tril(dists)
	dists = dists.reshape(n**2, 1)

	width_x = np.sqrt( 0.5 * np.median(dists[dists>0]) )
	# ----- -----

	# ----- width of X -----
	Ymed = Y

	G = np.sum(Ymed*Ymed, 1).reshape(n,1)
	Q = np.tile(G, (1, n) )
	R = np.tile(G.T, (n, 1) )

	dists = Q + R - 2* np.dot(Ymed, Ymed.T)
	dists = dists - np.tril(dists)
	dists = dists.reshape(n**2, 1)

	width_y = np.sqrt( 0.5 * np.median(dists[dists>0]) )
	# ----- -----

	bone = np.ones((n, 1), dtype = float)
	H = np.identity(n) - np.ones((n,n), dtype = float) / n

	K = rbf_dot(X, X, width_x)
	L = rbf_dot(Y, Y, width_y)

	Kc = np.dot(np.dot(H, K), H)
	Lc = np.dot(np.dot(H, L), H)

	testStat = np.sum(Kc.T * Lc) / n

	varHSIC = (Kc * Lc / 6)**2

	varHSIC = ( np.sum(varHSIC) - np.trace(varHSIC) ) / n / (n-1)

	varHSIC = varHSIC * 72 * (n-4) * (n-5) / n / (n-1) / (n-2) / (n-3)

	K = K - np.diag(np.diag(K))
	L = L - np.diag(np.diag(L))

	muX = np.dot(np.dot(bone.T, K), bone) / n / (n-1)
	muY = np.dot(np.dot(bone.T, L), bone) / n / (n-1)

	mHSIC = (1 + muX * muY - muX - muY) / n

	al = mHSIC**2 / varHSIC
	bet = varHSIC*n / mHSIC

	thresh = gamma.ppf(1-alph, al, scale=bet)[0][0]

	return (testStat, thresh)

In [8]:
import numpy
def centering(M):
    """
    Calculate the centering matrix
    """
    n = M.shape[0]
    unit = numpy.ones([n, n])
    identity = numpy.eye(n)
    H = identity - unit/n

    return numpy.matmul(M, H)

def gaussian_grammat(x, sigma=None):
    """
    Calculate the Gram matrix of x using a Gaussian kernel.
    If the bandwidth sigma is None, it is estimated using the median heuristic:
    ||x_i - x_j||**2 = 2 sigma**2
    """
    try:
        x.shape[1]
    except IndexError:
        x = x.reshape(x.shape[0], 1)

    xxT = numpy.matmul(x, x.T)
    xnorm = numpy.diag(xxT) - xxT + (numpy.diag(xxT) - xxT).T
    if sigma is None:
        mdist = numpy.median(xnorm[xnorm!= 0])
        sigma = numpy.sqrt(mdist*0.5)


   # --- If bandwidth is 0, add machine epsilon to it
    if sigma==0:
        eps = 7./3 - 4./3 - 1
        sigma += eps

    KX = - 0.5 * xnorm / sigma / sigma
    numpy.exp(KX, KX)
    return KX

def dHSIC_calc(K_list):
    """
    Calculate the HSIC estimator in the general case d > 2, as in
    [2] Definition 2.6
    """
    if not isinstance(K_list, list):
        K_list = list(K_list)

    n_k = len(K_list)

    length = K_list[0].shape[0]
    term1 = 1.0
    term2 = 1.0
    term3 = 2.0/length

    for j in range(0, n_k):
        K_j = K_list[j]
        term1 = numpy.multiply(term1, K_j)
        term2 = 1.0/length/length*term2*numpy.sum(K_j)
        term3 = 1.0/length*term3*K_j.sum(axis=0)

    term1 = numpy.sum(term1)
    term3 = numpy.sum(term3)
    dHSIC = (1.0/length)**2*term1+term2-term3
    return dHSIC

def HSIC(x, y):
    """
    Calculate the HSIC estimator for d=2, as in [1] eq (9)
    """
    n = x.shape[0]
    return numpy.trace(numpy.matmul(centering(gaussian_grammat(x)),centering(gaussian_grammat(y))))/n/n

def dHSIC(*argv):
    assert len(argv) > 1, "dHSIC requires at least two arguments"

    if len(argv) == 2:
        x, y = argv
        return HSIC(x, y)

    K_list = [gaussian_grammat(_arg) for _arg in argv]

    return dHSIC_calc(K_list)

In [9]:
leng = int(np.floor(wind_df.iloc[:,1].shape[0]/24))
hsic_val = np.zeros(leng)
stat = np.zeros(leng)
thre = np.zeros(leng)

In [12]:
for i in range(leng):
    x = np.array(wind_df.iloc[i*24:i*24+24, 2]).reshape(-1,1)
    y = np.array(wind_df.iloc[i*24:i*24+24, 1]).reshape(-1,1)
    hsic_val[i] = dHSIC(x, y)
    stat[i], thre[i] = hsic_gam(y, x, alph = 0.01)

In [13]:
hsic_val, stat, thre

(array([0.02167588, 0.02415444, 0.01412165, ..., 0.01546209, 0.0184563 ,
        0.03640786]),
 array([0.52022111, 0.57970644, 0.33891964, ..., 0.37109008, 0.4429511 ,
        0.87378857]),
 array([0.59713137, 0.68608822, 0.75427617, ..., 0.72074439, 0.65243973,
        0.648119  ]))

In [14]:
np.mean(hsic_val), np.mean(stat), np.mean(thre), np.sum(stat<thre)/leng*100

(0.01816994422505653,
 0.43607866140135676,
 0.6892333967436512,
 87.73972602739725)

In [15]:
leng

1460